on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write
  packages: read
  pull-requests: write
name: release-please

env:
  GH_TOKEN: ${{ github.token }} 
  RELEASE_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # - uses: googleapis/release-please-action@v4
      #   id: release
      #   with:
      #     token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
      - run: |
          npm i release-please -g
      - run: |
          release-please release-pr --repo-url $GITHUB_REPOSITORY --token=$RELEASE_TOKEN
      - run: |
          gh auth status
      - run: |
          release-please github-release --repo-url $GITHUB_REPOSITORY --token=$RELEASE_TOKEN --dry-run
        env:
          RELEASE_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          
          
        
