on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write
  packages: read
  pull-requests: write
name: release-please

env:
  GH_TOKEN: ${{ github.token }} 

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
      - run: |
          echo "PR CREATED:" ${{ steps.release.outputs.prs_created }}
      - run: |
          gh auth status
          
          
        
